#!/usr/bin/env bash
# --------------------( LICENSE                            )--------------------
# Copyright 2014-2016 by Alexis Pietak & Cecil Curry.
# See "LICENSE" for further details.
#
# --------------------( SYNOPSIS                           )--------------------
# This Bash shell script is a simple wrapper around BETSE's PyInstaller-based
# and setuptools-driven file freezer (i.e., command converting BETSE's CLI and
# GUI applications to platform-specific executable files). All arguments passed
# to this script are passed "as is" to that freezer.
#
# This script is defined as a Bash rather than Bourne script purely for the
# canonical ${BASH_SOURCE} string global, reliably providing the absolute path
# of this script and hence this script's directory.

# ....................{ PATHS                              }....................
# Absolute or relative path of this script.
script_filename="${BASH_SOURCE}"

# Absolute or relative path of this script's directory and hence BETSE's home.
betse_dirname="$(dirname "${script_filename}")"
# echo "BETSE home: ${betse_dirname}"

# ....................{ TESTS                              }....................
# Temoprarily change the current working directory to BETSE's home.
pushd "${betse_dirname}" >/dev/null

# Run BETSE's file freezer with all passed arguments.
python3 setup.py freeze_file "${@}"

# Revert the current working directory to the prior such directory.
popd >/dev/null
