# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'betse_test_1.ui'
#
# Created: Sat Dec 20 21:53:09 2014
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(818, 600)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../BioE/test/owl.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setIconSize(QtCore.QSize(50, 50))
        MainWindow.setTabShape(QtGui.QTabWidget.Rounded)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 30, 801, 511))
        self.tabWidget.setTabPosition(QtGui.QTabWidget.West)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setMovable(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_param = QtGui.QWidget()
        self.tab_param.setObjectName("tab_param")
        self.formLayoutWidget = QtGui.QWidget(self.tab_param)
        self.formLayoutWidget.setGeometry(QtCore.QRect(380, 10, 321, 195))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtGui.QFormLayout(self.formLayoutWidget)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.lbl_PNamem = QtGui.QLabel(self.formLayoutWidget)
        self.lbl_PNamem.setObjectName("lbl_PNamem")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.lbl_PNamem)
        self.le_PNamem = QtGui.QLineEdit(self.formLayoutWidget)
        self.le_PNamem.setText("1e-10")
        self.le_PNamem.setObjectName("le_PNamem")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.le_PNamem)
        self.lbl_PKmem = QtGui.QLabel(self.formLayoutWidget)
        self.lbl_PKmem.setObjectName("lbl_PKmem")
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.lbl_PKmem)
        self.le_PKmem = QtGui.QLineEdit(self.formLayoutWidget)
        self.le_PKmem.setText("1e-10")
        self.le_PKmem.setObjectName("le_PKmem")
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.le_PKmem)
        self.lbl_PClmem = QtGui.QLabel(self.formLayoutWidget)
        self.lbl_PClmem.setObjectName("lbl_PClmem")
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.lbl_PClmem)
        self.le_PClmem = QtGui.QLineEdit(self.formLayoutWidget)
        self.le_PClmem.setText("1e-10")
        self.le_PClmem.setObjectName("le_PClmem")
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.le_PClmem)
        self.lbl_PHmem = QtGui.QLabel(self.formLayoutWidget)
        self.lbl_PHmem.setObjectName("lbl_PHmem")
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.lbl_PHmem)
        self.le_PHmem = QtGui.QLineEdit(self.formLayoutWidget)
        self.le_PHmem.setText("1e-10")
        self.le_PHmem.setObjectName("le_PHmem")
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.le_PHmem)
        self.lbl_Camem = QtGui.QLabel(self.formLayoutWidget)
        self.lbl_Camem.setObjectName("lbl_Camem")
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.lbl_Camem)
        self.le_PCamem = QtGui.QLineEdit(self.formLayoutWidget)
        self.le_PCamem.setText("1e-10")
        self.le_PCamem.setObjectName("le_PCamem")
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.le_PCamem)
        self.lbl_DiffConsts = QtGui.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.lbl_DiffConsts.setFont(font)
        self.lbl_DiffConsts.setObjectName("lbl_DiffConsts")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.lbl_DiffConsts)
        self.formLayoutWidget_3 = QtGui.QWidget(self.tab_param)
        self.formLayoutWidget_3.setGeometry(QtCore.QRect(20, 10, 321, 262))
        self.formLayoutWidget_3.setObjectName("formLayoutWidget_3")
        self.formLayout_3 = QtGui.QFormLayout(self.formLayoutWidget_3)
        self.formLayout_3.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_3.setContentsMargins(0, 0, 0, 0)
        self.formLayout_3.setObjectName("formLayout_3")
        self.lbl_CellGenProp = QtGui.QLabel(self.formLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.lbl_CellGenProp.setFont(font)
        self.lbl_CellGenProp.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.lbl_CellGenProp.setObjectName("lbl_CellGenProp")
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.FieldRole, self.lbl_CellGenProp)
        self.lbl_rcell = QtGui.QLabel(self.formLayoutWidget_3)
        self.lbl_rcell.setObjectName("lbl_rcell")
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.LabelRole, self.lbl_rcell)
        self.le_rcell = QtGui.QLineEdit(self.formLayoutWidget_3)
        self.le_rcell.setText("5e-6")
        self.le_rcell.setObjectName("le_rcell")
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.FieldRole, self.le_rcell)
        self.lbl_tcellcell = QtGui.QLabel(self.formLayoutWidget_3)
        self.lbl_tcellcell.setObjectName("lbl_tcellcell")
        self.formLayout_3.setWidget(3, QtGui.QFormLayout.LabelRole, self.lbl_tcellcell)
        self.le_tcellcell = QtGui.QLineEdit(self.formLayoutWidget_3)
        self.le_tcellcell.setText("26e-9")
        self.le_tcellcell.setObjectName("le_tcellcell")
        self.formLayout_3.setWidget(3, QtGui.QFormLayout.FieldRole, self.le_tcellcell)
        self.lbl_Pgj = QtGui.QLabel(self.formLayoutWidget_3)
        self.lbl_Pgj.setObjectName("lbl_Pgj")
        self.formLayout_3.setWidget(4, QtGui.QFormLayout.LabelRole, self.lbl_Pgj)
        self.le_Pgj = QtGui.QLineEdit(self.formLayoutWidget_3)
        self.le_Pgj.setText("1e-8")
        self.le_Pgj.setObjectName("le_Pgj")
        self.formLayout_3.setWidget(4, QtGui.QFormLayout.FieldRole, self.le_Pgj)
        self.lbl_Dadh = QtGui.QLabel(self.formLayoutWidget_3)
        self.lbl_Dadh.setObjectName("lbl_Dadh")
        self.formLayout_3.setWidget(5, QtGui.QFormLayout.LabelRole, self.lbl_Dadh)
        self.le_Dadh = QtGui.QLineEdit(self.formLayoutWidget_3)
        self.le_Dadh.setText("1e-15")
        self.le_Dadh.setObjectName("le_Dadh")
        self.formLayout_3.setWidget(5, QtGui.QFormLayout.FieldRole, self.le_Dadh)
        self.lbl_vER = QtGui.QLabel(self.formLayoutWidget_3)
        self.lbl_vER.setObjectName("lbl_vER")
        self.formLayout_3.setWidget(6, QtGui.QFormLayout.LabelRole, self.lbl_vER)
        self.le_vER = QtGui.QLineEdit(self.formLayoutWidget_3)
        self.le_vER.setText("1e-25")
        self.le_vER.setObjectName("le_vER")
        self.formLayout_3.setWidget(6, QtGui.QFormLayout.FieldRole, self.le_vER)
        self.lbl_saER = QtGui.QLabel(self.formLayoutWidget_3)
        self.lbl_saER.setObjectName("lbl_saER")
        self.formLayout_3.setWidget(7, QtGui.QFormLayout.LabelRole, self.lbl_saER)
        self.le_saER = QtGui.QLineEdit(self.formLayoutWidget_3)
        self.le_saER.setText("1e-15")
        self.le_saER.setObjectName("le_saER")
        self.formLayout_3.setWidget(7, QtGui.QFormLayout.FieldRole, self.le_saER)
        self.formLayoutWidget_4 = QtGui.QWidget(self.tab_param)
        self.formLayoutWidget_4.setGeometry(QtCore.QRect(380, 230, 321, 271))
        self.formLayoutWidget_4.setObjectName("formLayoutWidget_4")
        self.formLayout_4 = QtGui.QFormLayout(self.formLayoutWidget_4)
        self.formLayout_4.setContentsMargins(0, 0, 0, 0)
        self.formLayout_4.setObjectName("formLayout_4")
        self.lbl_wrldx = QtGui.QLabel(self.formLayoutWidget_4)
        self.lbl_wrldx.setObjectName("lbl_wrldx")
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.LabelRole, self.lbl_wrldx)
        self.lbl_wrldy = QtGui.QLabel(self.formLayoutWidget_4)
        self.lbl_wrldy.setObjectName("lbl_wrldy")
        self.formLayout_4.setWidget(2, QtGui.QFormLayout.LabelRole, self.lbl_wrldy)
        self.lbl_Naenv = QtGui.QLabel(self.formLayoutWidget_4)
        self.lbl_Naenv.setObjectName("lbl_Naenv")
        self.formLayout_4.setWidget(3, QtGui.QFormLayout.LabelRole, self.lbl_Naenv)
        self.lbl_Kenv = QtGui.QLabel(self.formLayoutWidget_4)
        self.lbl_Kenv.setObjectName("lbl_Kenv")
        self.formLayout_4.setWidget(4, QtGui.QFormLayout.LabelRole, self.lbl_Kenv)
        self.lbl_Clenv = QtGui.QLabel(self.formLayoutWidget_4)
        self.lbl_Clenv.setObjectName("lbl_Clenv")
        self.formLayout_4.setWidget(5, QtGui.QFormLayout.LabelRole, self.lbl_Clenv)
        self.lbl_Caenv = QtGui.QLabel(self.formLayoutWidget_4)
        self.lbl_Caenv.setObjectName("lbl_Caenv")
        self.formLayout_4.setWidget(6, QtGui.QFormLayout.LabelRole, self.lbl_Caenv)
        self.lbl_Henv = QtGui.QLabel(self.formLayoutWidget_4)
        self.lbl_Henv.setObjectName("lbl_Henv")
        self.formLayout_4.setWidget(7, QtGui.QFormLayout.LabelRole, self.lbl_Henv)
        self.le_wrldx = QtGui.QLineEdit(self.formLayoutWidget_4)
        self.le_wrldx.setText("200e-6")
        self.le_wrldx.setObjectName("le_wrldx")
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.FieldRole, self.le_wrldx)
        self.le_wrldy = QtGui.QLineEdit(self.formLayoutWidget_4)
        self.le_wrldy.setText("200e-6")
        self.le_wrldy.setObjectName("le_wrldy")
        self.formLayout_4.setWidget(2, QtGui.QFormLayout.FieldRole, self.le_wrldy)
        self.le_Naenv = QtGui.QLineEdit(self.formLayoutWidget_4)
        self.le_Naenv.setText("145.0")
        self.le_Naenv.setObjectName("le_Naenv")
        self.formLayout_4.setWidget(3, QtGui.QFormLayout.FieldRole, self.le_Naenv)
        self.le_Kenv = QtGui.QLineEdit(self.formLayoutWidget_4)
        self.le_Kenv.setText("5.0")
        self.le_Kenv.setObjectName("le_Kenv")
        self.formLayout_4.setWidget(4, QtGui.QFormLayout.FieldRole, self.le_Kenv)
        self.le_Clenv = QtGui.QLineEdit(self.formLayoutWidget_4)
        self.le_Clenv.setText("105.0")
        self.le_Clenv.setObjectName("le_Clenv")
        self.formLayout_4.setWidget(5, QtGui.QFormLayout.FieldRole, self.le_Clenv)
        self.le_Caenv = QtGui.QLineEdit(self.formLayoutWidget_4)
        self.le_Caenv.setText("1.0")
        self.le_Caenv.setObjectName("le_Caenv")
        self.formLayout_4.setWidget(6, QtGui.QFormLayout.FieldRole, self.le_Caenv)
        self.le_Henv = QtGui.QLineEdit(self.formLayoutWidget_4)
        self.le_Henv.setText("1.0e-7")
        self.le_Henv.setObjectName("le_Henv")
        self.formLayout_4.setWidget(7, QtGui.QFormLayout.FieldRole, self.le_Henv)
        self.lbl_WorldProperties = QtGui.QLabel(self.formLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.lbl_WorldProperties.setFont(font)
        self.lbl_WorldProperties.setObjectName("lbl_WorldProperties")
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.FieldRole, self.lbl_WorldProperties)
        self.formLayoutWidget_2 = QtGui.QWidget(self.tab_param)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(20, 300, 321, 195))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_2 = QtGui.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.lbl_alphaNaK = QtGui.QLabel(self.formLayoutWidget_2)
        self.lbl_alphaNaK.setObjectName("lbl_alphaNaK")
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.lbl_alphaNaK)
        self.le_alphaNaK = QtGui.QLineEdit(self.formLayoutWidget_2)
        self.le_alphaNaK.setText("1.0e-17")
        self.le_alphaNaK.setObjectName("le_alphaNaK")
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.le_alphaNaK)
        self.lbl_CaATPase = QtGui.QLabel(self.formLayoutWidget_2)
        self.lbl_CaATPase.setObjectName("lbl_CaATPase")
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.lbl_CaATPase)
        self.le_alphaCa = QtGui.QLineEdit(self.formLayoutWidget_2)
        self.le_alphaCa.setText("1.0e-17")
        self.le_alphaCa.setObjectName("le_alphaCa")
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.le_alphaCa)
        self.lbl_alphaER = QtGui.QLabel(self.formLayoutWidget_2)
        self.lbl_alphaER.setObjectName("lbl_alphaER")
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.LabelRole, self.lbl_alphaER)
        self.le_alphaER = QtGui.QLineEdit(self.formLayoutWidget_2)
        self.le_alphaER.setText("1.0e-17")
        self.le_alphaER.setObjectName("le_alphaER")
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.FieldRole, self.le_alphaER)
        self.lbl_GATP = QtGui.QLabel(self.formLayoutWidget_2)
        self.lbl_GATP.setObjectName("lbl_GATP")
        self.formLayout_2.setWidget(4, QtGui.QFormLayout.LabelRole, self.lbl_GATP)
        self.le_deltaGATP = QtGui.QLineEdit(self.formLayoutWidget_2)
        self.le_deltaGATP.setText("-55")
        self.le_deltaGATP.setObjectName("le_deltaGATP")
        self.formLayout_2.setWidget(4, QtGui.QFormLayout.FieldRole, self.le_deltaGATP)
        self.lbl_T = QtGui.QLabel(self.formLayoutWidget_2)
        self.lbl_T.setObjectName("lbl_T")
        self.formLayout_2.setWidget(5, QtGui.QFormLayout.LabelRole, self.lbl_T)
        self.le_temp = QtGui.QLineEdit(self.formLayoutWidget_2)
        self.le_temp.setText("310")
        self.le_temp.setObjectName("le_temp")
        self.formLayout_2.setWidget(5, QtGui.QFormLayout.FieldRole, self.le_temp)
        self.label = QtGui.QLabel(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.label)
        self.tabWidget.addTab(self.tab_param, "")
        self.tab_geom = QtGui.QWidget()
        self.tab_geom.setObjectName("tab_geom")
        self.graphicsView_Geom = QtGui.QGraphicsView(self.tab_geom)
        self.graphicsView_Geom.setGeometry(QtCore.QRect(360, 10, 400, 400))
        self.graphicsView_Geom.setProperty("cursor", QtCore.Qt.ArrowCursor)
        self.graphicsView_Geom.setObjectName("graphicsView_Geom")
        self.tabWidget.addTab(self.tab_geom, "")
        self.tab_tiss = QtGui.QWidget()
        self.tab_tiss.setObjectName("tab_tiss")
        self.tabWidget.addTab(self.tab_tiss, "")
        self.tab_dyna = QtGui.QWidget()
        self.tab_dyna.setObjectName("tab_dyna")
        self.tabWidget.addTab(self.tab_dyna, "")
        self.tab_simu = QtGui.QWidget()
        self.tab_simu.setObjectName("tab_simu")
        self.verticalLayoutWidget = QtGui.QWidget(self.tab_simu)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(40, 0, 701, 491))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.graphicsView_simu = QtGui.QGraphicsView(self.verticalLayoutWidget)
        self.graphicsView_simu.setObjectName("graphicsView_simu")
        self.verticalLayout.addWidget(self.graphicsView_simu)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_pause = QtGui.QPushButton(self.verticalLayoutWidget)
        self.btn_pause.setObjectName("btn_pause")
        self.horizontalLayout.addWidget(self.btn_pause)
        self.btn_go = QtGui.QPushButton(self.verticalLayoutWidget)
        self.btn_go.setObjectName("btn_go")
        self.horizontalLayout.addWidget(self.btn_go)
        self.btn_stop = QtGui.QPushButton(self.verticalLayoutWidget)
        self.btn_stop.setObjectName("btn_stop")
        self.horizontalLayout.addWidget(self.btn_stop)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.tabWidget.addTab(self.tab_simu, "")
        self.tab_resu = QtGui.QWidget()
        self.tab_resu.setObjectName("tab_resu")
        self.comboBox_results = QtGui.QComboBox(self.tab_resu)
        self.comboBox_results.setGeometry(QtCore.QRect(20, 70, 151, 21))
        self.comboBox_results.setObjectName("comboBox_results")
        self.comboBox_results.addItem("")
        self.comboBox_results.addItem("")
        self.comboBox_results.addItem("")
        self.comboBox_results.addItem("")
        self.comboBox_results.addItem("")
        self.comboBox_results.addItem("")
        self.comboBox_results.addItem("")
        self.comboBox_results.addItem("")
        self.comboBox_results.addItem("")
        self.comboBox_results.addItem("")
        self.comboBox_results.addItem("")
        self.lbl_comboboxtitle = QtGui.QLabel(self.tab_resu)
        self.lbl_comboboxtitle.setGeometry(QtCore.QRect(30, 50, 91, 17))
        self.lbl_comboboxtitle.setObjectName("lbl_comboboxtitle")
        self.graphicsView_tissue = QtGui.QGraphicsView(self.tab_resu)
        self.graphicsView_tissue.setGeometry(QtCore.QRect(220, 10, 541, 431))
        self.graphicsView_tissue.setObjectName("graphicsView_tissue")
        self.tabWidget.addTab(self.tab_resu, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 818, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "BETSE 0.1", None, QtGui.QApplication.UnicodeUTF8))
        MainWindow.setToolTip(QtGui.QApplication.translate("MainWindow", "BioElectric Tissue Simulation Engine", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_PNamem.setToolTip(QtGui.QApplication.translate("MainWindow", "Na+ membrane permeability", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_PNamem.setText(QtGui.QApplication.translate("MainWindow", "PNa_mem [m/s]", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_PKmem.setToolTip(QtGui.QApplication.translate("MainWindow", "K+ membrane permeability", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_PKmem.setText(QtGui.QApplication.translate("MainWindow", "PK_mem [m/s]", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_PClmem.setToolTip(QtGui.QApplication.translate("MainWindow", "Cl- membrane permeability", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_PClmem.setText(QtGui.QApplication.translate("MainWindow", "PCl_mem [m/s]", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_PHmem.setToolTip(QtGui.QApplication.translate("MainWindow", "H+ membrane permeability", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_PHmem.setText(QtGui.QApplication.translate("MainWindow", "PH_mem [m/s]", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_Camem.setToolTip(QtGui.QApplication.translate("MainWindow", "Ca2+ membrane permeability", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_Camem.setText(QtGui.QApplication.translate("MainWindow", "PCa_mem [m/s]", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_DiffConsts.setText(QtGui.QApplication.translate("MainWindow", "Membrane Permeability", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_CellGenProp.setText(QtGui.QApplication.translate("MainWindow", "Cell General Properties", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_rcell.setToolTip(QtGui.QApplication.translate("MainWindow", "cell radius", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_rcell.setText(QtGui.QApplication.translate("MainWindow", "r_cell [m]", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_tcellcell.setToolTip(QtGui.QApplication.translate("MainWindow", "cell-cell separation", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_tcellcell.setText(QtGui.QApplication.translate("MainWindow", "t_cellcell [m]", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_Pgj.setToolTip(QtGui.QApplication.translate("MainWindow", "Gap junction permeability", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_Pgj.setText(QtGui.QApplication.translate("MainWindow", "P_gj [m/s]", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_Dadh.setToolTip(QtGui.QApplication.translate("MainWindow", "extracellular space diffusion constant", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_Dadh.setText(QtGui.QApplication.translate("MainWindow", "D_adh [m2/s]", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_vER.setToolTip(QtGui.QApplication.translate("MainWindow", "volume of endoplasmic reticulum", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_vER.setText(QtGui.QApplication.translate("MainWindow", "v_ER [m3]", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_saER.setToolTip(QtGui.QApplication.translate("MainWindow", "surface area of endoplasmic reticulum", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_saER.setText(QtGui.QApplication.translate("MainWindow", "sa_ER [m2]", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_wrldx.setToolTip(QtGui.QApplication.translate("MainWindow", "world x-dimension", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_wrldx.setText(QtGui.QApplication.translate("MainWindow", "world_x [m]", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_wrldy.setToolTip(QtGui.QApplication.translate("MainWindow", "world y-dimension", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_wrldy.setText(QtGui.QApplication.translate("MainWindow", "world_y [m]", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_Naenv.setText(QtGui.QApplication.translate("MainWindow", "cNa_env [mol/m3]", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_Kenv.setText(QtGui.QApplication.translate("MainWindow", "cK_env [mol/m3]", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_Clenv.setText(QtGui.QApplication.translate("MainWindow", "cCl_env [mol/m3]", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_Caenv.setText(QtGui.QApplication.translate("MainWindow", "cCa_env [mol/m3]", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_Henv.setText(QtGui.QApplication.translate("MainWindow", "cH_env [mol/m3]", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_WorldProperties.setText(QtGui.QApplication.translate("MainWindow", "Cells Properties", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_alphaNaK.setToolTip(QtGui.QApplication.translate("MainWindow", "rate constant Na-K-ATPase pump", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_alphaNaK.setText(QtGui.QApplication.translate("MainWindow", "alpha_NaKATPase [1/s]", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_CaATPase.setToolTip(QtGui.QApplication.translate("MainWindow", "rate constant Ca-ATPase pump", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_CaATPase.setText(QtGui.QApplication.translate("MainWindow", "alpha_CaATPase [1/s]", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_alphaER.setToolTip(QtGui.QApplication.translate("MainWindow", "rate constant for Ca2+ pump in ER", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_alphaER.setText(QtGui.QApplication.translate("MainWindow", "alpha_ER [1/s]", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_GATP.setToolTip(QtGui.QApplication.translate("MainWindow", "free energy in ATP hydrolysis", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_GATP.setText(QtGui.QApplication.translate("MainWindow", "deltaG_ATP [kJ/mol]", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_T.setToolTip(QtGui.QApplication.translate("MainWindow", "Temperature", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_T.setText(QtGui.QApplication.translate("MainWindow", "T [K]", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Active Transport", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_param), QtGui.QApplication.translate("MainWindow", "Parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_geom), QtGui.QApplication.translate("MainWindow", "Geometry", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_tiss), QtGui.QApplication.translate("MainWindow", "Tissues", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_dyna), QtGui.QApplication.translate("MainWindow", "TissueHandler", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_pause.setText(QtGui.QApplication.translate("MainWindow", "Pause", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_go.setText(QtGui.QApplication.translate("MainWindow", "Go", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_stop.setText(QtGui.QApplication.translate("MainWindow", "Stop", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_simu), QtGui.QApplication.translate("MainWindow", "Simulation", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_results.setItemText(0, QtGui.QApplication.translate("MainWindow", "Vmem", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_results.setItemText(1, QtGui.QApplication.translate("MainWindow", "Voltage", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_results.setItemText(2, QtGui.QApplication.translate("MainWindow", "Current", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_results.setItemText(3, QtGui.QApplication.translate("MainWindow", "P_gj", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_results.setItemText(4, QtGui.QApplication.translate("MainWindow", "cNa", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_results.setItemText(5, QtGui.QApplication.translate("MainWindow", "cK", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_results.setItemText(6, QtGui.QApplication.translate("MainWindow", "cCl", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_results.setItemText(7, QtGui.QApplication.translate("MainWindow", "cCa", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_results.setItemText(8, QtGui.QApplication.translate("MainWindow", "cH", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_results.setItemText(9, QtGui.QApplication.translate("MainWindow", "E-field", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_results.setItemText(10, QtGui.QApplication.translate("MainWindow", "H-field", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_comboboxtitle.setText(QtGui.QApplication.translate("MainWindow", "Choose plot:", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_resu), QtGui.QApplication.translate("MainWindow", "Results", None, QtGui.QApplication.UnicodeUTF8))

