#!/usr/bin/env python3
# --------------------( LICENSE                            )--------------------
# Copyright 2014-2016 by Alexis Pietak & Cecil Curry
# See "LICENSE" for further details.

'''
High-level constants describing BETSE's filesystem usage.

These constants provide the absolute paths of files and directories intended for
general use by both the CLI and GUI. For portability, such constants are
initialized in a system-aware manner guaranteed to be sane under various
installation environments -- including PyInstaller-frozen executables and
`setuptools`-installed script wrappers.
'''

# ....................{ IMPORTS                            }....................
import pkg_resources, sys
from betse import metadata
from betse.util.path import dirs, files, paths
from betse.util.os import oses
from os import environ, path

# ....................{ CONSTANTS ~ dir                    }....................
#FIXME: Replace all existing calls to os.path.expanduser() with this constant.

HOME_DIRNAME = None   # initialized below
'''
Absolute path of the current user's home directory.
'''


DOT_DIRNAME = None  # initialized below
'''
Absolute path of BETSE's dot directory in the current user's home directory.

This directory contains application-external resources (e.g., configuration
files) created at application runtime and subsequently editable by external
users and utilities.

Locations
----------
This path is operating system-specific as follows:

* Under Linux, this is `~/.betse/`. BETSE does _not_ currently comply with the
  _XDG Base Directory Specification (e.g., `~/.local/share/betse`), which the
  principal authors of BETSE largely regard as unuseful -- if not harmful.
* Under OS X, this is `~/Library/Application Support/betse`.
* Under Windows, this is
  `C:\Documents and Settings\${User}\Application Data\betse`.

.. _XDG Base Directory Specification: http://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html
'''

# ....................{ CONSTANTS ~ data                   }....................
DATA_DIRNAME = None   # initialized below
'''
Absolute path of BETSE's data directory.

Such directory contains application-internal resources (e.g., media files)
frozen with the end-user executable binaries generated by PyInstaller.
'''


DATA_YAML_DIRNAME = None   # initialized below
'''
Absolute path of BETSE's YAML data directory.

Such directory contains YAML configuration files and all ancillary files
referenced within the former.
'''


DATA_GEOMETRY_DIRNAME = None   # initialized below
'''
Absolute path of the application-wide geometry data directory.

This directory contains sample images intended to be used as input geometries in
tissue simulation configuration files. Each image defines a cell cluster shape
typically corresponding to some species (e.g., planaria) or organ (e.g., heart),
complete with internal cellular structure and exterior cellular boundary. Each
spatial subdivision of this shape is then associated with a real-world tissue
profile in the configuration file(s) referencing this image.
'''

# ....................{ CONSTANTS ~ file                   }....................
LOG_DEFAULT_FILENAME = None   # initialized below
'''
Absolute path of BETSE's default user-specific logfile.

This is the plaintext file to which BETSE logs all messages by default.
'''


PROFILE_DEFAULT_FILENAME = None   # initialized below
'''
Absolute path of BETSE's default user-specific profile dumpfile.

This is the binary file to which BETSE writes profiled statistics by default.
'''


CONFIG_DEFAULT_FILENAME = None   # initialized below
'''
Absolute path of BETSE's default application-wide configuration file.

This is the YAML file defining the default tissue simulation configuration.
'''

# ....................{ INITIALIZATION                     }....................
def init() -> None:
    '''
    Validate core directories and files required at program startup and
    initialize the corresponding module constants (e.g., `DOT_DIRNAME`).

    This function automatically creates non-existent paths where feasible and
    otherwise raises exceptions on such paths *not* being found or *not* having
    correct metadata (e.g., permissions).

    Such paths are required by both the CLI and GUI interfaces for BETSE. To
    support caller-specific exception handling, this function *must* be manually
    called early in program startup.
    '''

    # Define top-level *BEFORE* sub-level pathnames, as the latter depend upon
    # the former.
    _init_pathnames_top()
    _init_pathnames_sub()

    # Validate these pathnames.
    _test_pathnames()


def _init_pathnames_top() -> None:
    '''
    Define all top-level pathnames (e.g., `DOT_DIRNAME`) declared by this
    module as global constants.
    '''

    # Declare these constants to be globals, permitting modification below.
    global HOME_DIRNAME, DOT_DIRNAME, DATA_DIRNAME

    # Absolute path of the current user's home directory.
    HOME_DIRNAME = path.expanduser('~')

    # Initialize the absolute path of betse's dot directory.
    #
    # If the current system is OS X, set such directory accordingly.
    if oses.is_os_x():
        DOT_DIRNAME = paths.join(
            HOME_DIRNAME,
            'Library', 'Application Support',
            metadata.SCRIPT_NAME_CLI
        )
    # If the current system is Windows, set such directory accordingly.
    elif oses.is_windows():
        DOT_DIRNAME = paths.join(environ['APPDATA'], metadata.NAME)
    #FIXME: Explicitly assert POSIX compatibility here.
    # Else, assume the current system to be POSIX-compatible.
    else:
        DOT_DIRNAME = paths.join(HOME_DIRNAME, '.' + metadata.SCRIPT_NAME_CLI)

    # Relative path of the top-level data directory.
    data_root_basename = 'data'

    # Initialize the absolute path of betse's data directory.
    #
    # If the current application is a PyInstaller-frozen executable binary,
    # defer to the the PyInstaller-specific private attribute "_MEIPASS" added
    # to the canonical "sys" module by the PyInstaller bootloader embedded in
    # such binary. This attribute provides the absolute path of the temporary
    # directory containing all application data resources extracted from such
    # binary by such bootloader. "And it's turtles all the way down."
    if hasattr(sys, '_MEIPASS'):
        DATA_DIRNAME = paths.join(sys._MEIPASS, data_root_basename)
    # If the current application is a setuptools-installed script wrapper, the
    # data directory will have been preserved as is in the setuptools-installed
    # copy of the current Python package tree. In such case, query setuptools to
    # obtain such directory's path in a cross-platform manner. See also:
    #     https://pythonhosted.org/setuptools/pkg_resources.html
    elif pkg_resources.resource_isdir(__name__, data_root_basename):
        DATA_DIRNAME = pkg_resources.resource_filename(
            __name__, data_root_basename)
    # Else, the current application is either setuptools-symlinked script
    # wrapper *OR* was invoked via the hidden "python3 -m betse.cli.cli"
    # command. In either case, such directory's path is directly obtainable
    # relative to the absolute path of the current module.
    else:
        DATA_DIRNAME = paths.join(
            paths.get_dirname(__file__), data_root_basename)


def _init_pathnames_sub() -> None:
    '''
    Define all top-level pathnames (e.g., `DOT_DIRNAME`) declared by this
    module as global constants.
    '''

    # Declare these constants to be globals, permitting modification below.
    global\
        DATA_GEOMETRY_DIRNAME,\
        LOG_DEFAULT_FILENAME, PROFILE_DEFAULT_FILENAME, CONFIG_DEFAULT_FILENAME

    # Initialize the absolute paths of data subdirectories.
    DATA_YAML_DIRNAME = paths.join(DATA_DIRNAME, 'yaml')
    DATA_GEOMETRY_DIRNAME = paths.join(DATA_YAML_DIRNAME, 'geo')

    # Initialize the absolute paths of data files.
    CONFIG_DEFAULT_FILENAME = paths.join(DATA_YAML_DIRNAME, 'sim_config.yaml')

    # Absolute path of the default user-specific logfile and profile dumpfile.
    LOG_DEFAULT_FILENAME = paths.join(
        DOT_DIRNAME, metadata.SCRIPT_NAME_CLI + '.log')
    PROFILE_DEFAULT_FILENAME = paths.join(
        DOT_DIRNAME, metadata.SCRIPT_NAME_CLI + '.prof')


def _test_pathnames() -> None:
    '''
    Validate all pathnames (e.g., `DOT_DIRNAME`) declared by this module.
    '''

    # Ensure all requisite paths exist.
    dirs.die_unless_dir(DATA_DIRNAME, DATA_GEOMETRY_DIRNAME)
    files.die_unless_file(CONFIG_DEFAULT_FILENAME)

    # Create BETSE's top-level dot directory if not found.
    dirs.make_unless_dir(DOT_DIRNAME)
